# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14product_schema.proto\x12\x07product\"O\n\rProductRating\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x12\x0e\n\x06review\x18\x04 \x01(\t\"\x89\x02\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05stock\x18\x06 \x01(\x05\x12\x13\n\x06\x65xpiry\x18\x07 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x62rand\x18\x08 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06weight\x18\t \x01(\x02H\x02\x88\x01\x01\x12\x10\n\x03sku\x18\n \x01(\tH\x03\x88\x01\x01\x12\'\n\x07ratings\x18\x0b \x01(\x0b\x32\x16.product.ProductRatingB\t\n\x07_expiryB\x08\n\x06_brandB\t\n\x07_weightB\x06\n\x04_sku\"G\n\x13Intailise_Inventory\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTRATING._serialized_start=33
  _PRODUCTRATING._serialized_end=112
  _PRODUCT._serialized_start=115
  _PRODUCT._serialized_end=380
  _INTAILISE_INVENTORY._serialized_start=382
  _INTAILISE_INVENTORY._serialized_end=453
# @@protoc_insertion_point(module_scope)
