# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n\x06Status\x12\"\n\x05value\x18\x01 \x01(\x0e\x32\x13.order.Status.Value\"4\n\x05Value\x12\x0b\n\x07PENDING\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\"\xaf\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x14\n\x0ctotal_amount\x18\x05 \x01(\x02\x12\x1d\n\x06status\x18\x06 \x01(\x0b\x32\r.order.Status\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=55
  _STATUS._serialized_end=153
  _STATUS_VALUE._serialized_start=101
  _STATUS_VALUE._serialized_end=153
  _ORDER._serialized_start=156
  _ORDER._serialized_end=331
# @@protoc_insertion_point(module_scope)
